apiVersion: v1
kind: PersistentVolume
metadata:
  name: resource-service-pv
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"