apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap }}
  namespace: {{ .Values.namespace }}
  labels:
    date: {{ include "current-date" . | quote }}
    version: {{ include "version-label" . | quote }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db-service:5432/postgres"
  song.service.url: "http://songService:8081/"
  init-script.sql: |
    CREATE TABLE IF NOT EXISTS users (
         id INT PRIMARY KEY, 
         username VARCHAR (50) NOT NULL,
         email VARCHAR(100) NOT NULL);