apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.songService.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.songService.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.songService.port }}
      targetPort: {{ .Values.songService.port }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.songService.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.songService.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.songService.name }}
    spec:
      containers:
        - name: {{ .Values.songService.name }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap }}
          image: {{ .Values.songService.image.repository }}:{{ .Values.songService.image.tag }}
          ports:
            - containerPort: {{ .Values.songService.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap }}
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password