apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource-service-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
