apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource-service-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: resource-service-pvc
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: app-config
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /resources/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /resources/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
          volumeMounts:
            - mountPath: "/mnt/data"
              name: data-volume
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: song.service.url
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: song.service.url
